Feature/items
eln2/eln2 pull request #115
Opened 2021-02-18 08:17 UTC by AlanFletes

Added all the ore chunk items and the correspondig loot tables for the drops. Also, the lang file has been updated with the name of the blocks and items added in past pulls.

2021-02-23 03:37 UTC, Caeleron commented
Noticed a few ores were added that duplicate existing Minecraft ores. In particular, diamond, lignite and native gold are duplicates of Minecraft's diamond, coal and gold ore respectively. Native copper wasn't a duplicate, but since we ultimately will be targetting 1.17, which does have it, I see it as a duplicate ore.

2021-02-23 03:39 UTC, jrddunbr commented
We should keep the copper ore for now. The rest can be removed.

2021-02-23 03:48 UTC, jrddunbr requested changes
This and the comments above about duplicates; remove all of the duplicates except for the native copper ore. We will remove that when we are actually on 1.17.

2021-02-23 03:48 UTC, jrddunbr commented on integration-mc1-16/src/main/kotlin/org/eln2/ChunkItems.kt
> +    MULTIMETER(MultimeterItem()),
This is not a chunk item and should be added in a new enum class called `MiscItems`.

2021-02-23 03:48 UTC, jrddunbr commented on integration-mc1-16/src/main/kotlin/org/eln2/ModBlocks.kt
> +class ModBlocks {
This class can be deleted.

2021-02-23 03:48 UTC, jrddunbr commented on integration-mc1-16/src/main/kotlin/org/eln2/ModItems.kt
> +class ModItems {
This class can be deleted

2021-02-23 03:48 UTC, jrddunbr commented on integration-mc1-16/src/main/kotlin/org/eln2/utils/OreData.kt
> + * Very Common 98 - 120)
This needs units, for example, ore veins per chunk.

2021-02-28 07:18 UTC, jrddunbr commented
I can't seem to find the registration location for the Flubber block. But this change is definitely a step in the right direction.

2021-02-28 16:02 UTC, jrddunbr commented
I just did a force push with a complete rebase of all of the commits that were here. Going to start testing.

2021-02-28 17:29 UTC, jrddunbr approved these changes
LGTM. Fixed the item texture for Flubber and did some quick registry edits in another commit.

2021-02-28 17:30 UTC, merged