Rotation system
eln2/eln2 pull request #142
Opened 2022-02-10 17:48 UTC by empireu

basic rotation system to get a demo up and running.

2022-02-10 18:03 UTC, Caeleron requested changes

2022-02-10 18:03 UTC, Caeleron commented on src/main/java/org/eln2/mc/common/Mathematics.kt
> +        return kotlin.math.atan2(y1 - y0, x1 - x0) * 180.0 / Math.PI
Please use radians.

2022-02-10 18:03 UTC, Caeleron commented on src/main/java/org/eln2/mc/common/PlacementRotation.kt
> +        return absoluteToRelative[direction]!!
Can this be converted into a `return when` statement? That way we don't need to create a HashMap for every instance of this.

2022-02-10 18:10 UTC, Caeleron commented on src/main/java/org/eln2/mc/common/Mathematics.kt
> +        return kotlin.math.atan2(y1 - y0, x1 - x0) * 180.0 / Math.PI
Apparently MC uses degrees. The JDK doesn't provide library functions for degrees so this will just have to do. Nevermind me.

2022-02-10 18:28 UTC, Caeleron submitted a review, later dismissed

2022-02-12 17:53 UTC, jrddunbr commented
I'll fix the conflicts if they are still here when I actually do this merge. Wanted to get rotation into the `dev` branch.

2022-02-12 19:37 UTC, jrddunbr requested changes
Yep.

2022-02-12 19:37 UTC, jrddunbr commented on src/main/java/org/eln2/mc/client/overlay/plotter/PlotterOverlay.kt
> +object PlotterOverlay : IIngameOverlay {
`do not use object` ... followed by an object. What's the comment for?

2022-02-12 19:37 UTC, jrddunbr commented on src/main/java/org/eln2/mc/client/input/Input.kt
> +// String category
What is this documenting? If it's the KeyMapping, might as well add a Javadoc comment for it

2022-02-12 19:40 UTC, jrddunbr commented
Steps to reproduce:

1. Edit `./run/eula.txt` to have `true` for the EULA
2. Run server (might need to run server to generate EULA file) as below:

```
./gradlew runServer
```

Resulting error:

```
java.lang.ExceptionInInitializerError: null
        at java.lang.Class.forName0(Native Method) ~[?:?] {}
        at java.lang.Class.forName(Class.java:467) ~[?:?] {}
        at thedarkcolour.kotlinforforge.AutoKotlinEventBusSubscriber.inject(AutoKotlinEventBusSubscriber.kt:76) ~[kotlinforforge-3.0.0.jar%2395!:3.0.0] {}
        at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:76) ~[kotlinforforge-3.0.0.jar%2395!:3.0.0] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18-38.0.16.jar%2391!:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.18-38.0.16.jar:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.24.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.24.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.24.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at org.eln2.mc.client.input.Input.<clinit>(Input.kt:23) ~[%2392!:?] {re:classloading}
        ... 12 more
[14:38:29] [main/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
```

2022-02-12 22:10 UTC, jrddunbr approved these changes
LGTM, tested with real client and real server with no issues in multiplayer.

2022-02-12 22:13 UTC, merged